### ISSUE TITLE
Watching video results in previous screen showing in "black bands"

### ISSUE THREAD

**Issue by dougbelkofer** [bennettpeter/mythtv#1]
When selecting a video to play, once it starts, you can see portions of the last screen you were on in the "black band" area at the top and bottom of the screen after the video starts.

**Comment by dougbelkofer** [comment]
By the way - thank you SOOO much for the work to create a Raspberry Pi compatible version of the MythTV frontend!

**Comment by bennettpeter** [comment]
This has been fixed
https://code.mythtv.org/trac/ticket/12691
However it still happens if you select ffmpeg or have no mpeg2 license The fix for that one is ready but not yet released
https://code.mythtv.org/trac/ticket/12693

Peter
