### ISSUE TITLE
Program Details do not display

### ISSUE THREAD

**Issue by bluetrekker** [bennettpeter/mythtv#2]
On the Watch Recordings screen, the "i" key displays the Program Details screen, but no details show for any recordings.

Backend is 0.27.4-31-gaa256d1 from SCRPMs running on Fedora 19
Frontend is 0.27.6-83-g88be65f on Raspberry Pi 3

**Comment by bennettpeter** [comment]
Can you tell me what theme you are using.

**Comment by bluetrekker** [comment]
MythCenter Wide

**Comment by bennettpeter** [comment]
OK I see the problem - it is actually happening in all themes I have tried.  However it is fixed in 0.28 so I am not inclined to try to do anything to fix 0.27 at this stage.
