### ISSUE TITLE
audio out of sync, mythv .31

### ISSUE THREAD

**Issue by 0n3man** [bennettpeter/mythtv#5]
Loaded the capability on fire stick 4k.  Audio plays slightly ahead of video.  I set parameters based on your recommendations and I also tried others posted by another user of the capability with .31.  There is discussion on the web about a parameter that allows you to shift the audio, but it doesn't appear to exist in .31.  I have no such issue on my current frontends or with your leanfront on the same fire stick.  Any suggestion.  And thanks for your effort on both this and the leanfront.  Your implementations work better on an arm processor than of the others I've tried aimed at raspberry pi and odroid products.

**Comment by bennettpeter** [comment]
For mythfrontend, while playing, type menu (M)->Audio->Adjust audio sync. You can move the slider back and forth as needed. If you get audio stuttering, go to setup->Video->playback->Advanced and increase the value of Audio Read Ahead.
